#!/bin/bash

declare -i start=0
declare -i step=1
reverse=

while getopts "b:s:r" opt; do
 case $opt in
  b)
   [[ ${OPTARG} =~ [0-9]+$ ]] || { echo "Invalid argument"; exit 1; }
   start="${OPTARG}"
   ;;
  s)
   [[ ${OPTARG} =~ [0-9]+$ ]] || { echo "invalid arguemnts"; exit 1; }
   step="${OPTARG}"
   ;;
  :)
   echo "Option ${OPTATG} is missing an argument" 
   exit 1
   ;;
  r)
   reverse="yes"
   ;;
  \?)
   echo "Unknown argument!!!"
   exit 1
 esac
done

shift $(( ${OPTIND} -1 ))

[[ $1 ]] || { echo "missing last argument"; exit 1; }
[[ $1 =~ [0-9]+$ ]] || { echo "last argument is not a number"; exit 1; }

end=$1

if [[ ${reverse} ]]; then
 for (( i=end; i >= start; i-=step )); do
  echo "$i"
 done
else
 for (( i=start; i <= end; i+=step )); do
  echo $i
 done
fi

exit 0;
