#!/bin/bash

if [[ ! $# -gt 0 ]]; then
 echo Please provide a lenght argument
 exit 1
fi

if [[ ! $1 =~ [0-9]+$ ]]; then
 echo First argument must be number
 exit 1
fi

char="-"

if [[ $2 ]]; then
 char=$2
fi

line=

for (( i=0; i<$1; i++ )); do
 line=${line}${char}
done

printf "%s\n" ${line}
exit 0
