#!/bin/bash

[[ $# -ne 2 ]] && { echo "invalid arguments!!!" >&2; exit 1; }

#if [[ ! $# -eq 2 ]]; then
# echo "invalid arguments!!!"
# exit 1
#fi


for i in *"$1"; do
 base=$(basename "$i" "$1");
 mv $i ${base}$2
 #printf "mv %s %s\n" $i ${base}$2
done
exit 0
